org: suarezmanuel
app: firsttestserverless-app
service: aws-python-http-getTitle

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: python3.7

functions:
  getTitle:
    handler: handler.getTitle
    events:
      - http:
          path: getTitle
          method: get
